title: "Nix入門"
summary: |
  現代最強のパッケージマネージャNixを知ろう！

  Nixって何？と疑問に思っている方に向けて、Nixのコンセプトと仕組みを解説します。

  後編: 『Nix入門: ハンズオン編』（現在執筆中・公開日未定）
topics: ["nix"]
published: true
price: 0
chapters:
  - 01-introduction
  - 02-what-is-nix
  - 03-why-use-nix
  - 04-re-what-is-nix
  - 05-pure-functional-build
  - 06-nix-store
  - 07-binary-cache
  - 08-derivation
  - 09-nix-lang
  - 10-nixpkgs
  - 11-flakes
  - 12-profiles
  - 13-garbage-collection
  - 14-conclusion
